### ISSUE TITLE
Missing file or assembly Newtonsoft.Json

### ISSUE THREAD

**Issue by roydukkey** [aspnet/dotnet-watch#72] opened 2016-04-14 15:51 UTC
Currently getting an issue finding Newtonsoft.Json:

```
C:\Projects\test>dotnet watch
[DotNetWatcher] fail: Error(s) reading project file 'C:\Projects\test\project.json':
[DotNetWatcher] fail: Could not load file or assembly 'Newtonsoft.Json, Version=7.0.0.0,
Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies.
The system cannot find the file specified.
[DotNetWatcher] info: Fix the error to continue.
^C
C:\Projects\test>dotnet --version
1.0.0-rc2-002374
```

The project restores and builds without issue for the follow project.json and NuGet.config.

##### project.json
```json
{
	"dependencies": {
		"src": "0.1.0-*",
		"Microsoft.AspNetCore.Diagnostics": "1.0.0-*",
		"Microsoft.AspNetCore.HttpOverrides": "1.0.0-*",
		"Microsoft.AspNetCore.Server.Kestrel": "1.0.0-*",
		"Microsoft.NETCore.App": {
			"type": "platform",
			"version": "1.0.0-rc2-23931"
		}
	},
	"frameworks": {
		"netcoreapp1.0": {
			"imports": [
				"portable-net45+wp80+win8+wpa81+dnxcore50"
			]
		}
	},

	"compilationOptions": {
		"emitEntryPoint": true,
		"debugType": "portable"
	},

	"tools": {
		"dotnet-watch": "1.0.0-*"
	}
}
```

##### NuGet.config
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
	<packageSources>
		<clear />
		<add key="AspNetCIDev" value="https://www.myget.org/F/aspnetcidev/api/v3/index.json" />
		<add key="NuGet" value="https://api.nuget.org/v3/index.json" />
	</packageSources>
</configuration>
```

**Comment by muratg** [comment] 2016-04-14 17:04
@victorhurdugaci

**Comment by victorhurdugaci** [comment] 2016-04-14 17:43
I can reproduce this. Investigating...

**Comment by victorhurdugaci** [comment] 2016-04-14 19:02
The fix is to add `imports` to the tool and re-restore (make sure you clear the packages folder first because it doesn't work otherwise):

```
"tools": {
        "dotnet-watch": {
           "version": "1.0.0-*",
           "imports": "portable-net451+win8"
        }
    }
```

We believe this will be fixed in a future CLI

**Closed by victorhurdugaci** 2016-04-14 19:02 UTC
Labels: 2 - Working

**Comment by dealdiane** [comment] 2016-04-27 10:56
@victorhurdugaci  On a mac, where can I find this packages folder that needs to be cleared? I deleted `~/.local/share/NuGet/*` but it still errors.

**Comment by victorhurdugaci** [comment] 2016-04-27 19:32
it should be under `~/.nuget`

**Comment by dealdiane** [comment] 2016-04-27 19:38
Yep, that worked. Thanks
