### ISSUE TITLE
OSX: dotnet watch run fails

### ISSUE THREAD

**Issue by vinaydate** [aspnet/dotnet-watch#119] opened 2016-05-30 06:58 UTC
When I run dotnet watch run, the command fails with following log:

    $ dotnet -v watch run
    Telemetry is: Enabled
    Running /usr/local/share/dotnet/dotnet exec --depsfile /Users/vinay/.nuget/packages/.tools/Microsoft.DotNet.Watcher.Tools/1.0.0-preview1-final/netcoreapp1.0/Microsoft.DotNet.Watcher.Tools.deps.json --additionalprobingpath /Users/vinay/.nuget/packages /Users/vinay/.nuget/packages/Microsoft.DotNet.Watcher.Tools/1.0.0-preview1-final/lib/netcoreapp1.0/dotnet-watch.dll run
    Process ID: 5562
    [DotNetWatcher] fail: Error(s) reading project file '/Users/vinay/Documents/Development/Projects/dnc-test/project.json': 
    [DotNetWatcher] fail: Could not load file or assembly 'Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
    [DotNetWatcher] info: Fix the error to continue.

My environment:
> OS X version: 10.11.5 (15F34)
$ dotnet --version
1.0.0-preview1-002702

project.json:

    {
      "version": "1.0.0-*",
      "buildOptions": {
        "emitEntryPoint": true
      },
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.0.0-rc2-3002702"
        },
        "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-rc2-final"    
      },
      "frameworks": {
        "netcoreapp1.0": {
          "imports": "dnxcore50"
        }
      },
      "tools": {
        "Microsoft.DotNet.Watcher.Tools": {
          "version": "1.0.0-*",
          "imports": "portable-net451+win8"
        }
      }
    }

startup.cs:

    public class Startup
    {
        public void Configure(IApplicationBuilder app)
        {
            app.Run(context =>
            {
                return context.Response.WriteAsync("Helo from ASP.NET Core!!!!");
            });
        }
    }

program.cs:

    public class Program
    {
        public static void Main(string[] args)
        {
            var host = new WebHostBuilder()
                .UseKestrel()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseStartup<Startup>()
                .UseUrls("http://0.0.0.0:5001/")
                .Build();

            host.Run();
        }
    }

**Comment by victorhurdugaci** [comment] 2016-05-31 16:27
@vinaydate I cannot reproduce your issue. Can you please share a bit more information:

1. What nuget feeds do you use?
2. What version of `dotnet-watch` do you use?

**Comment by victorhurdugaci** [comment] 2016-05-31 18:30
Ah, nevermind, I see in the log that you shared `Microsoft.DotNet.Watcher.Tools/1.0.0-preview1-final`. You're using an old dotnet watcher. Go the the packages folder and delete it, then run `dotnet restore`

**Comment by muratg** [comment] 2016-06-02 21:40
@vinaydate did moving to RC2 dotnet watcher fix the issue?

**Comment by vinaydate** [comment] 2016-06-03 17:01
> Go to the packages folder and delete it, then run dotnet restore

@victorhurdugaci It may look naive, but I am newbie to this cross-platform dotnet thing, so, where does this 'packages' folder reside? I tried to find it, but no such folder in my project root.

@muratg, forgive me for ignorance. I am using RC2 of dot net core, but don't know how to get RC2 of watcher

**Comment by victorhurdugaci** [comment] 2016-06-03 17:03
To delete the packages folder, delete `/Users/vinay/.nuget/packages/`. You'll get the latest package when you run `dotnet restore`

**Comment by vinaydate** [comment] 2016-06-03 18:28
@victorhurdugaci and @muratg Fixed by deleting packages folder n restoring again. Thank you.

**Closed** 2016-06-03 18:29 UTC
