### ISSUE TITLE
dnx-watch doesn't see changes when running in a VirtualBox machine, when the files are shared from the host machine

### ISSUE THREAD

**Issue by jamesmarnoch** [aspnet/dotnet-watch#55] opened 2016-03-01 09:31 UTC
I've tried this on both a Ubuntu guest machine with coreclr and Windows Server 2012 guest machine with coreclr.

When the files are shared from the host to the guest machine, dnx-watch doesn't catch any changes.

If I copy the project (HelloMvc from the samples) from the mounted share to somewhere else on the guest machine, dnx-watch does catch changes.

**Comment by muratg** [comment] 2016-03-02 23:28
Interesting, looks like a file system issue.  @victorhurdugaci, should this bug be moved to dotnet/corefx?

**Comment by muratg** [comment] 2016-03-03 17:21
@joshfree Do you know of any file watcher differences in VM scenarios?

**Comment by joshfree** [comment] 2016-03-03 17:36
I know that historically the underlying win32 apis for FSW have been unreliable, at least in previous versions of Windows; you definitely could not count on them for anything mission critical.  I'm unaware of any issues specific to the Ubuntu scenario above.

**Comment by glennc** [comment] 2016-03-30 05:35
Has someone looked at this to know where the problem is? If it is an issue with the filesystem watcher when using Core CLR then we need to know that and have a bug filed for it. I am told this works on Mono so my assumption is that it is a corefx problem.

**Comment by friism** [comment] 2016-04-07 00:48
@glennc there are some scenarios where I don't think FilesystemWatcher is going to work. Examples:

 * [VirtualBox shared folder](https://www.virtualbox.org/ticket/10660) (used by Docker Toolbox on Windows)
 * [Samba shares](http://stackoverflow.com/questions/11306302/filesystemwatcher-with-samba-on-linux) (currently used by Docker for Windows)

... I'd actually be very interested in knowing whether this works with the new Windows-Subsystem-for-Linux stuff, eg. does a Linux process watching a file get an inotify event if a Windows process makes a change (I don't have access to Win 10 build with WSL yet).

A workaround would be for dotnet-watch to have a fallback polling mode. [Nodemon has that](https://github.com/remy/nodemon#application-isnt-restarting).

Other links:

 * https://github.com/remy/nodemon/issues/74

**Comment by friism** [comment] 2016-04-07 00:50
Looks like the corefx folks have already looked at this: https://github.com/dotnet/corefxlab/tree/master/src/System.IO.FileSystem.Watcher.Polling

**Comment by glennc** [comment] 2016-04-07 23:52
To fix this we are going to implement a polling IFileWatcher.

The watcher should poll all files so that it can work on network shares.
It should not be the default.
Setting an env variable should enable it. (`DOTNET_WATCH_MODE=poll` perhaps?)
Passing an option on the command line should also allow you to set it

This way in a Docker base image you can use `ENV DOTNET_WATCH_MODE=poll` or you can pass it on the command line in a Dockerfile.

This is presumably not just Docker, another common scenarios is where you use a VM to do dev work but your code is in a share. A Windows VM on a Linux or OS X machine for example.

@victorhurdugaci you good to implement it?

**Comment by muratg** [comment] 2016-04-08 00:16
@glennc sounds good. I think a better env var name would be `DOTNET_WATCH_POLL` which could be set to 1 or true (or whatever pattern we use these days for boolean env vars).

**Comment by victorhurdugaci** [comment] 2016-04-08 00:23
I think I prefer the argument route. something like `--poll`. For example:

`dotnet watch --poll -- --app-arg1 --app-arg2`

Btw, should polling be the default behavior?

**Comment by friism** [comment] 2016-04-08 00:29
> Btw, should polling be the default behavior?

That may not be advisable because polling is not performant, especially with larger apps: https://github.com/OmniSharp/omnisharp-roslyn/pull/81

/cc @davidfowl

**Comment by glennc** [comment] 2016-04-08 00:43
Yeah, it can't be the default.

I was also just reminded that MVC is going to use FileSystemWatcher for detecting changes to cshtml as well. So we might not be able to go down this path either. The change needs to be wider.

**Comment by victorhurdugaci** [comment] 2016-04-12 18:45
I have a PR out to fix this: https://github.com/aspnet/dotnet-watch/issues/55

**Comment by friism** [comment] 2016-04-12 18:47
Link to PR: https://github.com/aspnet/dotnet-watch/pull/66

**Comment by victorhurdugaci** [comment] 2016-04-13 17:46
Changes were merged both in dev and release. If you want to watch files on a mounted volume, you have to set `USE_POLLING_FILE_WATCHER=true` before running `dotnet watch`

**Closed by victorhurdugaci** 2016-04-13 17:46 UTC
Labels: 2 - Working
